In [1]:
import numpy as np
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [4]:
np.arange(5,10) 

array([5, 6, 7, 8, 9])

In [5]:
np,.arange(1,100)

SyntaxError: invalid syntax (1462185587.py, line 1)

In [6]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
np.arange(1,31,5)


array([ 1,  6, 11, 16, 21, 26])

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.zeros((1,5),int)

array([[0, 0, 0, 0, 0]])

In [13]:
np.linspace(0,2,5)
# lindspace is linear spaced#

array([0. , 0.5, 1. , 1.5, 2. ])

In [14]:
np.eye(0,2,5)
#

array([], shape=(0, 2), dtype=float64)

In [15]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
np.random.rand(3,5)


array([[0.21659976, 0.58844377, 0.61669258, 0.22564543, 0.90302929],
       [0.60961072, 0.85823171, 0.21956112, 0.43477714, 0.43880719],
       [0.69505539, 0.00626783, 0.19988916, 0.02513668, 0.99034306]])

In [19]:
arr=np.random.randn(2,4)
arr

array([[ 0.56215141, -0.0147397 , -1.18576823,  1.07543204],
       [ 0.32525211, -0.04277801,  0.50252956,  1.81586864]])

In [20]:
np.random.randint(2,100)

37

In [21]:
np.random.randint(20,56,100)

array([35, 30, 35, 52, 48, 47, 46, 45, 23, 54, 23, 37, 50, 20, 37, 52, 33,
       47, 40, 30, 35, 29, 41, 53, 54, 30, 32, 29, 30, 50, 27, 50, 27, 30,
       30, 20, 31, 49, 45, 39, 22, 25, 51, 42, 41, 28, 31, 35, 51, 40, 42,
       35, 52, 20, 21, 39, 53, 37, 55, 28, 45, 55, 34, 51, 55, 43, 41, 53,
       55, 41, 51, 37, 53, 42, 55, 55, 50, 31, 32, 31, 53, 40, 23, 55, 53,
       46, 49, 52, 29, 47, 26, 30, 26, 26, 27, 41, 33, 39, 28, 45])

In [22]:
in_array=np.arange(30)
in_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
rand_array=np.random.randint(0,100,20)
rand_array

array([73, 98, 42,  9, 92, 64, 86, 58, 55, 37, 65,  4, 46, 93, 96, 49, 16,
       46, 10, 26])

In [25]:
in_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [29]:
in_array.reshape(2,3)

ValueError: cannot reshape array of size 30 into shape (2,3)

In [30]:
rand_array.max()


98

In [32]:
rand_array.argmax()

1

In [34]:
a.T

NameError: name 'a' is not defined

In [35]:
a_array=np.arange(10,21)
a_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:

a_array[0]

10

In [38]:
a_array[2:5]

array([12, 13, 14])

In [39]:
a_array[1:4]=100
a_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [40]:
a_array[0:7]

array([ 10, 100, 100, 100,  14,  15,  16])

In [41]:
subset_array=a_array[0:7]
subset_array

array([ 10, 100, 100, 100,  14,  15,  16])

In [43]:
sample_matrix=np.array([[50,20,1,23],[29,35,45,43],[9,89,87,76]])
sample_matrix

array([[50, 20,  1, 23],
       [29, 35, 45, 43],
       [ 9, 89, 87, 76]])

In [44]:
sample_matrix[1,2]

45

In [45]:
sample_matrix[2,:]

array([ 9, 89, 87, 76])

In [46]:
sample_matrix[2]

array([ 9, 89, 87, 76])

In [47]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [43, 45],
       [76, 87]])